/*This library provides useful macros and functions
 * for interacting with the Comparator E 0 module.
 *
 * This module takes an input clock at 24 MHz, takes
 * and input signal at P8.0 and is compared to
 * voltage generated by the included reference voltage
 * generator.
 *
 * The output of this comparator can be observed on P7.1
 *
 *  Created on: May 29, 2021
 *      Author: Janelle & Zarek
 */

#ifndef COMPE_H_
#define COMPE_H_

#ifndef MSP_H_
#include "msp.h"
#endif

/*Port for + input (C1) of CE0*/
#define COMPE_INPORT P8
#define COMPE_INPIN  BIT0

/*Port for analyzing the output of CE0*/
#define COMPE_OUTPORT  P7
#define COMPE_OUTPIN   BIT1

/*Used for anding with desired threshold voltages*/
#define COMPE_FIVEBITS 0x1F

void COMPE_init(void);
void COMPE_change_thresh(uint8_t lo, uint8_t hi);
void COMPE_debug(void);

#endif /* COMPE_H_ */
